# Generated by Django 6.0.6 on 2026-06-23 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_is_free_delivery_product_is_trending_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['trending_order', '-created_date']},
        ),
        migrations.AddField(
            model_name='product',
            name='trending_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls display order in Trending (1 = first). Slots 2–8 are the small cards.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False, help_text='Check to include this product in the Trending section.'),
        ),
        migrations.CreateModel(
            name='TrendingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_ends_at', models.DateTimeField(blank=True, help_text='When this offer expires. Leave blank to hide the countdown.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one TrendingSection should be active at a time.')),
                ('offer_product', models.ForeignKey(blank=True, help_text='The product shown in the big left card with the countdown timer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_configs', to='store.product')),
            ],
            options={
                'verbose_name': 'Trending Section Config',
                'verbose_name_plural': 'Trending Section Config',
            },
        ),
    ]
