# Generated by Django 6.0.6 on 2026-06-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_categories',
            field=models.ManyToManyField(blank=True, help_text='Hold down Ctrl (or Cmd on Mac) to select multiple.', related_name='extra_products', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_products', to='store.category'),
        ),
    ]
